### ISSUE TITLE
Fail to parse expressions with non-range step values

### ISSUE THREAD

**Issue by shaolang** [maennchen/crontab#123]
hi,

The current version fails to parse expressions with non-range step values, even though the library's [examples page](https://hexdocs.pm/crontab/cron_notation.html#examples) suggest otherwise. For example, the following all return `{:error, "Can't parse 0 as a range"}`

```
Crontab.CronExpression.Parser.parse "0 0/5 14 * * *"    # example from library's example page
Crontab.CronExpression.Parse.parse "0/2 * * * *"
```

I can get around the issue by using ranges, e.g., `0-23/5` and `0-59/2` respectively for the examples above.

I can help in submitting a fix, if supporting such expressions is expected.

**Comment by maennchen** [comment]
Oh, you're right. A PR would be welcome.

I think it's suppused to work as follows: `REMAINDER/DIVIDER` and evaluates as truthy if `INTERVAL % DIVIDER == REMAINDER`

**Comment by shaolang** [comment]
> Oh, you're right. A PR would be welcome.
> 
> I think it's suppused to work as follows: `REMAINDER/DIVIDER` and evaluates as truthy if `INTERVAL % DIVIDER == REMAINDER`

I think START/INTERVAL means run on START + INTERVAL * N where N begins at 0; for example, if `0 0 2/5 * * *` (i.e., for the day of month field) and today is 2024-01-30, that expression's next few run dates would be:

- 2024-02-02 00:00:00
- 2024-02-07 00:00:00
- 2024-02-12 00:00:00
- 2024-02-17 00:00:00
- 2024-02-22 00:00:00
- 2024-02-27 00:00:00
- 2024-03-02 00:00:00
