### ISSUE TITLE
Supported cron expressions?

### ISSUE THREAD

**Issue by kenny-evitt** [maennchen/crontab#66]
Thanks for this library! It's great!

I'm just curious if there's a *specific* cron expression reference for Crontab?

Maybe the cron expression section in the cron Wikipedia article is good enough?:

 - [CRON expression – cron - Wikipedia](https://en.wikipedia.org/wiki/Cron#CRON_expression)

The parser tests are very informative:

 - [crontab/parser_test.exs at master · jshmrtn/crontab](https://github.com/jshmrtn/crontab/blob/master/test/crontab/cron_expression/parser_test.exs)

An overview of supported expressions would be nice. Are you open to someone adding a docs page? Or adding that info to an existing page?

**Comment by maennchen** [comment]
@kenny-evitt I‘m definitely open for some more docs.

I tried to find the original resources I used, can‘t find them anymore though.

I think that all details should be in the tests though like you said.

**Comment by maennchen** [comment]
Documented here: https://hexdocs.pm/crontab/cron_notation.html

**Comment by kenny-evitt** [comment]
@maennchen The new docs are _very_ nice!
